name: Create APK Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Assemble release with Gradle
        run: chmod +x gradlew &&./gradlew assembleRelease
      - name: Sign APK
        run: jarsigner -verbose -keystore jtykey.jks -storepass ${{ secrets.STORE_PASS }} `find app/build/outputs/apk/release/ -name *.apk` zerokirby
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: false
            prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: app/build/outputs/apk/release/ProgressNote-${{ steps.create_release.inputs.tag_name }}.apk
         asset_name: ProgressNote-${{ steps.create_release.inputs.tag_name }}.apk
         asset_content_type: application/vnd.android.package-archive
